### ISSUE TITLE
AWS SDK dependency is old, causing regional failures for CMH and possibly others

### ISSUE THREAD

**Issue by LimpingNinja** [awslabs/aws-devops-essential#1]
The project currently has a dependency on 1.10.10 in the pom.xml; CMH wasn't released until 1.11.44. If you deploy to CMH you will get a failure in ValidateService and browsing to the application will return a 500 error referencing the fact that no region was selected.

https://aws.amazon.com/releasenotes/release-aws-sdk-for-java-1-11-44/?tag=releasenotes%23keywords%23java

This is easily resolved by modifying the pom.xml with support for the latest sdk (1.11.319). The concern here is that when a user gets to the point of failure they are pretty far along in the exercise and changing the dependency at this point is a little more work on clean-up and outside the scope of training, catching it before this phase is much easier.

**Comment by karthiksambandam-zz** [comment]
Updated the version to 1.11.44. Thank you.
