### ISSUE TITLE
Type 

### ISSUE THREAD

**Issue by sridharsemail** [awslabs/aws-devops-essential#3]
1. Infrastructure is misspelled in the tutorial as Insfrastrture in Additional Exercises.
"Stage 1: Pipeline + Infrastrture as code"

2. Add the following step in your $git commands so that you don't have to enter gnarly user id/password every time.
Store your git credentials:
$ git config credential.helper store 
// thanks to the instructor

**Comment by karthiksambandam-zz** [comment]
Thank guys. Fixed it.
