### ISSUE TITLE
Suggestion for clearer instructions

### ISSUE THREAD

**Issue by Ramias1** [awslabs/aws-devops-essential#4]
Lab 4, stage 2:

> For User parameters, specify the Public DNS address for the Amazon EC2 DevWebApp01 instance you copied earlier (for example, http://ec2-52-62-36-220.ap-southeast-2.compute.amazonaws.com), and then choose Add action.

Please consider changing to:
`For User parameters, specify **http://** and the Public DNS address for the Amazon EC2 DevWebApp01 instance you copied earlier (for example, http://ec2-52-62-36-220.ap-southeast-2.compute.amazonaws.com), and then choose Add action.`

The Lambda function fails without this, requiring cycling through the entire pipeline again.  Yes, the example shows http://, but explicitly calling it out would help.

Thanks

**Comment by karthiksambandam-zz** [comment]
Added the comments. Thanks.
