### ISSUE TITLE
Inability to Stop and Start an DevWebApp01 and ProdWebApp01 Instances

### ISSUE THREAD

**Issue by mwhitlow** [awslabs/aws-devops-essential#8]
At the end of the AWS DevOps Day class last week, I stop the DevWebApp01 and ProdWebApp01 instances that I creased in labs 1 and 2.  When I got home, I started them and started on Lab #3.  In  Stage 1 step 9 the Staging event fails because the ApplicationStop Event failed on the DevWebApp01 instance here is the log: 

Error CodeScriptFailed
Script Namescripts/stop_application
MessageScript at specified location: scripts/stop_application failed with exit code 1
Log TailLifecycleEvent - ApplicationStop
Script - scripts/stop_application

I stopped the server and ran it again, this also failed.  

Sam Hennessy replied to my e-mail, and suggested that "easiest way to troubleshoot is to sign on to the machine, and look into the /opt/code-deploy directory.  There will be a folder that matches up with the code deploy deployment.  You can take a look in that folder, and run the script that seems to be failing."  I soon discovered that I was not able to login the instances, because I do not have the Key Pair for the DevWebApp01 and ProdWebApp01 instances.  I check my download folder and no PEN file was download during the tutorial. 

Can you please make the default server creation methods, use a Key Pair that the student already has or creates inappropriate lab, thus allow in the student access to the server such that they can examine it.  This may not be appropriate for a fully optimized DevOps system, but for someone trying to learn the system it would be highly beneficial. 

Sincerely yours, 
Marc Whitlow

**Comment by karthiksambandam-zz** [comment]
Hi Marc,
Thanks for providing feedback. I reviewed your request. Though your concern seems validate from a learner's perspective. But it would affect the follow of this lab. So I create a separate template for you to use for debugging the instance.
https://s3.amazonaws.com/devops-workshop-0526-2051/02-aws-devops-workshop-environment-setup-withKey.template
Thanks,
Karthik T
