### ISSUE TITLE
No Outputs in CloudFormation for Stack DevopsWorkshop-roles

### ISSUE THREAD

**Issue by mwhitlow** [awslabs/aws-devops-essential#9]
This is a continuation of Issue #8.

I decided to completely start over.  This time I created an new IAM user for AWS Labs, using the Aministrative IAM on this account, which I was using last time.  I delete everything that I had created in us-west-2, following the direction at the bottom of the main page.  I got to Lab 1 Step 4.  After running 
```
DevOps_Labs:~/environment/WebAppRepo (master) $ aws cloudformation create-stack --stack-name DevopsWorkshop-roles \
--template-body https://github.com/awslabs/aws-devops-essential/raw/master/templates/01-aws-devops-workshop-roles.template \
--capabilities CAPABILITY_IAM
{
    "StackId": "arn:aws:cloudformation:us-west-2:539564704580:stack/DevopsWorkshop-roles/036dd070-734b-11e8-b47f-50a68a0bca36"
}
```
I opened  CloudFormation looking for **BuildRoleArn-Value-FROM-CLOUDFORMATION-OUTPUT**, but no Output was found, see attached.  
![nooutputfordevopsworkshop-roles](https://user-images.githubusercontent.com/2746288/41574845-71a68934-7336-11e8-9837-da3ac017f00e.png)

I repeated the process of deleting the DevopsWorkshop-roles stack, and got the same results.

**Comment by karthiksambandam-zz** [comment]
Hi Marc,
I could not recreate this issue. 
But i believe the rollback was not clean. There might be IAM roles still not removed during rollback. 
Also there will not be any output for rollback. You need to check Resources/Events section for cleanup completion. Thanks.
